[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
morph_contract = "morpn5gHTNsUivctAeGCEG9VBFqxoRpdDgmAfNQH3DM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "LLMrieZMpbJFwN52WgmBNMxYojrpRVYXdC1RCweEbab"
program = "tests/fixtures/llm.so"
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/metadata.so"
upgradeable = false

[[test.validator.account]]
address = "9uGkS41eWJvMeJ18ve6LdsDvd2fSotpH3vaiBZTzu5pP"
filename = "tests/fixtures/counter.json"

[[test.validator.account]]
address = "32pz61BKN7xvs9DMX3aF3We2udqhWWD7wD3QAkEa4wNV"
filename = "tests/fixtures/identity.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
